### ISSUE TITLE
Prioritization

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-streamgraph-explorer#91]
Required before public launch:

* [ ] Smaller font for smaller screens #89
* [ ] Work out data portal embedding #88
* [ ] Zero Padding #73
* [ ] Position Labels on Screen #75
* [ ] Update Y domain when zoomed #74
* [x] Reliable Resize Behavior #99
* [x] Add Origin and Destination Labels #81
  * [x] Implement Design for Desktop #2
  * [x] Implement Design for Mobile #3
* [x] Redesign Bars for Small Width #90
* [x] Top 20 should show conditionally #82
* [x] Context area should always span full time #87
* [x] Color Bars  #85
* [x] Consistent Colors #84

Doable after public launch:

* [ ] Remove text at the top? #94
* [ ] Pinned Year Interaction #61
* [ ] Linked Hovering? #86
* [ ] Pull Data from CKAN API #6
